export const PRODUCT_DATA_LOADING_COMPLETE = "PRODUCT_DATA_LOADING_COMPLETE";
export const PRODUCT_DATA_LOADING_ERROR = "PRODUCT_DATA_LOADING_ERROR";
export const CART_DATA_ADD = "CART_DATA_ADD";
export const REMOVE_CART_DATA = "REMOVE_CART_DATA";

